version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - python -m web_app.run_unit_tests
